### ISSUE TITLE
2019.3.1 Version

### ISSUE THREAD

**Issue by Mike-EEE** [matkoch/ReSharper.InternalsVisibleTo#16]
I tried installing this extension for 2019.3.1 but it was not available.

Please vote to improve the extension model experience so we don't have to continually nag extension authors for each release:

https://youtrack.jetbrains.com/issue/RSRP-459966

Thank you for any assistance you can provide towards this matter.

**Comment by Mike-EEE** [comment]
Out of the 16 extensions I use, this one and ReCommended for ReSharper (https://github.com/prodot/ReCommended-Extension/issues/42) are the only two extensions that are not available in `2019.3.1`.

**Comment by matkoch** [comment]
Published.
